name: Main action caller

on:
  [push]

jobs:
  workflow-1:
    uses: PhillipiLino/workflows/.github/workflows/second-action.yml@main

  # workflow-2:
  #   uses: GuillaumeFalourd/poc-github-actions/.github/workflows/48-reusable-workflow-2.yml@main

  # workflow-3:
  #   uses: GuillaumeFalourd/poc-github-actions/.github/workflows/48-reusable-workflow-3.yml@main