name: Send release informations
on:
  release:
    types: [published]
    branches:
        - main
        - 'release/**'
      
jobs:
  release:
    name: Send informations
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Get release version
        run: |
          echo "release_author=${{ github.event.release.author.login }}"
          echo "release_body=${{ github.event.release.body }}"
          echo "release_tag=${{ github.event.release.tag_name }}"

      - name: Slack Failure Notification
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          message: ":rotating_light: AUTHOR: ${{ github.event.release.author.login }} TAG: ${{ github.event.release.tag_name }}\n\n${{ github.event.release.body}}"
          webhook-url: ${{ secrets.SLACK_TEST_WEBHOOK }}
